---
title: "CV"
---

This is my CV.

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.

I have worked for the past few years and now I am back in school.

OBJECTIVE

Seeking a responsible and challenging career field that provides exposure to new ideas and stimulates personal and professional growth.

SUMMARY

-Ability to learn quickly -Motivated team player -Enthusiastic achiever -Energetic, Disciplined and loyal worker

EDUCATION

2011 - 2013 Collin County Community College, Plano, TX 75023 Associate of Applied Science Degree in Graphic Design (Web Track) Overall GPA 3.872/4.00

2003 - 2005 Collin County Community College, Plano, TX 75023 Associate of Applied Science Degree in Graphic Design Overall GPA 3.83/4.00

1998 - 2000 University of North Texas, Denton, TX 76201  BS in Business Computer Information Systems  Overall GPA 3.489/4.00

1996 - 1998 Collin County Community College, Plano, TX 75023 Associate Degree in Associate of Arts GPA 3.627/4.00 - Graduated with honors (Cum Laude)\

SKILLS

LANGUAGE . Fluent in English, Malay, Mandarin and Chinese dialects (Teochew, Hokkien and Cantonese)
